### ISSUE TITLE
Dav1dWarpedMotionParams_union_ ... include/dav1d/headers_h_100_5)" is not a valid Ident

### ISSUE THREAD

**Issue by boozook** [rust-av/dav1d-rs#88]
Build error:

```log
Caused by:
  process didn't exit successfully: `/Users/ak/Developer/Projects/comic-opt/target/debug/build/dav1d-sys-aca7d2f4fb623e90/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DAV1D_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-link-search=native=/opt/homebrew/Cellar/dav1d/1.2.1/lib
  cargo:rustc-link-lib=dav1d
  cargo:include=/opt/homebrew/Cellar/dav1d/1.2.1/include
  cargo:rerun-if-env-changed=SYSTEM_DEPS_BUILD_INTERNAL
  cargo:rerun-if-env-changed=SYSTEM_DEPS_LINK
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_LIB
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_LIB_FRAMEWORK
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_SEARCH_NATIVE
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_SEARCH_FRAMEWORK
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_INCLUDE
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_BUILD_INTERNAL
  cargo:rerun-if-env-changed=SYSTEM_DEPS_DAV1D_LINK

  cargo:rustc-cfg=system_deps_have_dav1d

  --- stderr
  thread 'main' panicked at /Users/ak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.69/src/fallback.rs:817:9:
  "Dav1dWarpedMotionParams_union_(unnamed_at_/opt/homebrew/Cellar/dav1d/1_2_1/include/dav1d/headers_h_100_5)" is not a valid Ident
  stack backtrace:
     0:        0x10541bbfc - std::backtrace_rs::backtrace::libunwind::trace::h71068c4b5b031286
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:        0x10541bbfc - std::backtrace_rs::backtrace::trace_unsynchronized::h56b9813f75d4d961
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x10541bbfc - std::sys_common::backtrace::_print_fmt::hb10f64f159882954
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x10541bbfc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h052d4a6449303d0c
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x10543a4a0 - core::fmt::rt::Argument::fmt::h670e0fc9dd75299f
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/fmt/rt.rs:142:9
     5:        0x10543a4a0 - core::fmt::write::hd7376fa11f842969
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/fmt/mod.rs:1117:17
     6:        0x1054193e0 - std::io::Write::write_fmt::h8962cd07816e935b
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/io/mod.rs:1762:15
     7:        0x10541ba38 - std::sys_common::backtrace::_print::h40815699fd9e306f
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/sys_common/backtrace.rs:47:5
     8:        0x10541ba38 - std::sys_common::backtrace::print::h97fb0a8a4077c481
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/sys_common/backtrace.rs:34:9
     9:        0x10541d15c - std::panicking::default_hook::{{closure}}::h3b4672ac61ca5355
    10:        0x10541cea4 - std::panicking::default_hook::h609e6a125a90b4e7
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:292:9
    11:        0x10541d584 - std::panicking::rust_panic_with_hook::h9625542414b348eb
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:779:13
    12:        0x10541d484 - std::panicking::begin_panic_handler::{{closure}}::hb4fa343c314105dc
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:657:13
    13:        0x10541c064 - std::sys_common::backtrace::__rust_end_short_backtrace::he263cec7b035e782
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/sys_common/backtrace.rs:170:18
    14:        0x10541d220 - rust_begin_unwind
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:645:5
    15:        0x105451db8 - core::panicking::panic_fmt::h624e311b541e9a0d
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/panicking.rs:72:14
    16:        0x1052ceb8c - proc_macro2::fallback::validate_ident::h4c1166d32a8af3ee
    17:        0x1052ce980 - proc_macro2::fallback::Ident::_new::h4e3824fcf317ea6c
    18:        0x1052ce9d4 - proc_macro2::fallback::Ident::new::h87977e32a16da4ac
    19:        0x1052d0b5c - proc_macro2::imp::Ident::new::h8af81837a8d2ca81
    20:        0x1052dbf44 - proc_macro2::Ident::new::h3aacf2d7a0886b32
    21:        0x104fea4f4 - bindgen::ir::context::BindgenContext::rust_ident_raw::h8e2d49afd883be3c
    22:        0x104fea480 - bindgen::ir::context::BindgenContext::rust_ident::hfa28c652e0112912
    23:        0x104fc0668 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h567d49f30da88ac3
    24:        0x104ffdea8 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hd4d2ed70c80c9bae
    25:        0x104f3965c - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2f17d85f3ef84ebe
    26:        0x104fc5ce4 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h567d49f30da88ac3
    27:        0x104ffdea8 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hd4d2ed70c80c9bae
    28:        0x104f3965c - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2f17d85f3ef84ebe
    29:        0x104fa93d8 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h4e6da4cc9fa13593
    30:        0x104f166c0 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::hda7427ff9d7e40fe
    31:        0x104f39644 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h2f17d85f3ef84ebe
    32:        0x104fb0200 - bindgen::codegen::codegen::{{closure}}::h7751c636f51e91ec
    33:        0x104fec210 - bindgen::ir::context::BindgenContext::gen::ha5e7209342cc78fe
    34:        0x104faf958 - bindgen::codegen::codegen::h5830481c624c1763
    35:        0x104fb413c - bindgen::Bindings::generate::hb6d8a3e8b68939e0
    36:        0x104fb2068 - bindgen::Builder::generate::hf5eebb5c4d84a3a1
    37:        0x104ed6b88 - build_script_build::main::h0bed91e13a0f84a2
    38:        0x104ed37f4 - core::ops::function::FnOnce::call_once::he4072fabf6d94ac4
    39:        0x104ed2ef4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2fab1ceea94ef536
    40:        0x104ed3030 - std::rt::lang_start::{{closure}}::h6e9ad04a80859b8f
    41:        0x105415210 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h07136ef239371295
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/ops/function.rs:284:13
    42:        0x105415210 - std::panicking::try::do_call::hc67f66b8c648ad32
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:552:40
    43:        0x105415210 - std::panicking::try::hf97491b0e67985d1
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:516:19
    44:        0x105415210 - std::panic::catch_unwind::h29050b1d23639a61
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panic.rs:142:14
    45:        0x105415210 - std::rt::lang_start_internal::{{closure}}::hcead3afc42fd36ce
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/rt.rs:148:48
    46:        0x105415210 - std::panicking::try::do_call::hc86b0a533f7b067b
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:552:40
    47:        0x105415210 - std::panicking::try::hb1cdabe993a5546d
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:516:19
    48:        0x105415210 - std::panic::catch_unwind::h21666380498b6e46
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panic.rs:142:14
    49:        0x105415210 - std::rt::lang_start_internal::h7be4efcec2e53815
                                 at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/rt.rs:148:20
    50:        0x104ed3008 - std::rt::lang_start::h34cef9998fbdbe32
    51:        0x104ed7024 - _main

```

**Comment by boozook** [comment]
Oh, I just found that it depends on new dav1d 1.3.0 that [not yet ready in brew](https://github.com/Homebrew/homebrew-core/pull/153725) 🥺

**Comment by sdroege** [comment]
You're also using an old version of dav1d-rs. Version 0.9 does not use bindgen anymore (but only works with dav1d < 1.3), and version 0.10 works with dav1d 1.3

**Comment by boozook** [comment]
@sdroege, unfortunately I not using dav1d-rs directly. It's in the deep of deps-tree.

```
image v0.24.7
├── bytemuck v1.14.0
├── byteorder v1.5.0
├── color_quant v1.1.0
├── dav1d v0.6.1
│   └── dav1d-sys v0.3.5
```

**Comment by sdroege** [comment]
You'll have to ask the `image` crate to update its dependency then. 0.6 is already quite ancient
